name: Build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger build on docker hub
      run: curl -d '' "${trigger_url}"
      env:
        trigger_url: ${{ secrets.DOCKER_HUB_BUILD_TRIGGER_URL }}
